name: Solar System Workflow
on: 
    workflow_dispatch: 
    push:
        branches:
            - main
            - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        strategy:
           matrix:
             nodejs_versions: [18, 19, 20]
             os: [ubuntu-latest, macos-latest]
             exclude:
               - nodejs_versions: 18
                 os: macos-latest
        name: Unit Testing
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup NodeJS Version - ${{ matrix.nodejs_versions }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.nodejs_versions }}

            - name: Install Deps.
              run: npm install
            
            - name: Unit Testing
              run: npm test

            - name: Upload Test Report
              uses: actions/upload-artifact@v4
              with:
                name: Mocha-Test-Result-version-${{ matrix.nodejs_versions }}
                path: test-results.xml
            

            